import type { WireFormat } from './types';

/**
 * The E2E oracle: a precomputed table of *real* Rust engine output, generated by
 * `cargo run -p mdcli -- export-fixtures`.
 *
 * Two kinds of entry share one flat table, so the mock backend has a single lookup path:
 * conversions keyed `"<from>:<to>:<input>"` holding a string, and scroll-sync outlines keyed
 * `"outline:<markdown>"` holding an array of 1-based source line numbers.
 *
 * The file is gitignored and is frequently absent (a fresh clone, a CI job that has not run the
 * exporter yet). That is not an error: a missing table degrades to passthrough so the UI still
 * runs. It is loaded lazily through `import.meta.glob`, which — unlike a static or dynamic
 * `import()` of a literal path — resolves to an empty record instead of failing the build when
 * the file does not exist.
 */
export type OracleValue = string | number[];

export type Oracle = Readonly<Record<string, OracleValue>>;

type OracleModule = { default: Oracle };

const modules = import.meta.glob<OracleModule>('../test-support/oracle.json');

let pending: Promise<Oracle> | null = null;

/** Build the conversion lookup key the Rust exporter uses. */
export function oracleKey(from: WireFormat, to: WireFormat, input: string): string {
  return `${from}:${to}:${input}`;
}

/** Build the outline lookup key the Rust exporter uses. */
export function outlineKey(markdown: string): string {
  return `outline:${markdown}`;
}

/**
 * Load the oracle table once. Resolves to `{}` when the file is missing or malformed —
 * callers fall back to passthrough.
 */
export function loadOracle(): Promise<Oracle> {
  if (pending) return pending;
  const loaders = Object.values(modules);
  const loader = loaders[0];
  if (!loader) {
    pending = Promise.resolve({});
    return pending;
  }
  pending = loader()
    .then((mod) => mod.default ?? {})
    .catch(() => ({}) as Oracle);
  return pending;
}

/** Forget the cached table. Unit tests only. */
export function resetOracle(): void {
  pending = null;
}
