import { defineConfig, devices } from "@playwright/test";

/**
 * Functional tests for the Richochet UI.
 *
 * Playwright drives a browser, not the Tauri webview, so the app runs against its `mock`
 * conversion backend — a replay of real Rust engine output generated by `just oracle`. Conversion
 * *correctness* is covered exhaustively by the Rust corpus; what these tests exist to catch is the
 * class of bug unit tests cannot reach: caret theft, sync loops, stale async responses landing out
 * of order, copy actions wiring the wrong payload, and layout breaking at small window sizes.
 */
export default defineConfig({
  testDir: "./e2e",
  fullyParallel: true,
  forbidOnly: !!process.env.CI,
  retries: process.env.CI ? 2 : 0,
  workers: process.env.CI ? 1 : undefined,
  reporter: process.env.CI ? [["html"], ["list"]] : "list",
  timeout: 15_000,
  expect: { timeout: 5_000 },

  use: {
    baseURL: "http://localhost:5173",
    trace: "on-first-retry",
    // The app is a fixed-size desktop utility; this is the default window from tauri.conf.json.
    viewport: { width: 1100, height: 720 },
  },

  projects: [{ name: "chromium", use: { ...devices["Desktop Chrome"] } }],

  webServer: {
    command: "pnpm vite dev --port 5173 --strictPort",
    url: "http://localhost:5173",
    reuseExistingServer: !process.env.CI,
    stdout: "ignore",
    stderr: "pipe",
    timeout: 60_000,
  },
});
